title: All Passport Stamps
description: > # this means to ignore newlines until "baseurl:"
  Documenting what I have experienced > Country Count: 25
permalink: ':title/'
baseurl: ""
url: ""
site-twitter:

# Author Settings
author: "All Passport Stamps"
author-img: profile_2.jpg
about-author: "Jason's Country Count: 29\nDocumenting what I have learned"
social-instagram: 
social-twitter:
social-facebook:
social-github:
social-linkedin:
social-email:

# Disqus
discus-identifier: all-passport-stamps

# Tracker
analytics: G-28R21NWK60

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
